n = str(input('Digite o seu nome completo '))
i1 = n.upper()
print('Esse nome em maíusculo fica {}'.format(i1))
i2 = n.lower()
print('Esse nome em minúsculo fica {}'.format(i2))
i3 = n.split()
i4 = ''.join(i3)
print('Esse nome tem {} caractéres'.format(len(i4)))
print('O seu primeiro nome é {}.'.format(i3[0]))
