n1 = float(input('Digite um número '))
n2 = float(input('Digite outro número '))
n3 = float(input('Digite outro número '))
n4 = float(input('Digite o último número '))
lista = (n1, n2, n3, n4)
print(lista.count(9))